# Generated by Django 5.0.7 on 2024-08-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(db_index=True, max_length=100)),
                ('nick_name', models.CharField(db_index=True, max_length=50)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('address', models.TextField(db_index=True)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('village', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('taluka', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('date_of_birth', models.DateField(db_index=True)),
                ('age', models.IntegerField(db_index=True)),
                ('contact_number', models.CharField(db_index=True, max_length=15)),
                ('place_of_birth', models.CharField(db_index=True, max_length=100)),
                ('birth_time', models.TimeField(db_index=True)),
                ('nationality', models.CharField(db_index=True, max_length=50)),
                ('mother_tongue', models.CharField(db_index=True, max_length=50)),
                ('other_language', models.CharField(db_index=True, max_length=50)),
                ('cast', models.CharField(db_index=True, max_length=50)),
                ('sub_cast', models.CharField(db_index=True, max_length=50)),
                ('religion', models.CharField(db_index=True, max_length=50)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], db_index=True, max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], db_index=True, max_length=20)),
                ('blood_group', models.CharField(choices=[('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+')], db_index=True, max_length=10)),
                ('family_members', models.TextField(db_index=True)),
                ('pan_card', models.CharField(db_index=True, max_length=20)),
                ('driving_licence', models.CharField(db_index=True, max_length=20)),
                ('passport_number', models.CharField(db_index=True, max_length=20)),
                ('voting_id', models.CharField(db_index=True, max_length=20)),
                ('educational_details', models.TextField(db_index=True)),
                ('occupation', models.CharField(db_index=True, max_length=100)),
                ('level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, max_length=10, null=True)),
                ('main_photo', models.ImageField(upload_to='person_photos/')),
                ('case_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Solved', 'Solved')], db_index=True, default='Pending', max_length=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['person_name', 'nick_name'], name='personApp_p_person__e3e8aa_idx'), models.Index(fields=['latitude', 'longitude', 'address', 'pincode'], name='personApp_p_latitud_98b3e3_idx'), models.Index(fields=['village', 'city', 'taluka', 'district', 'state', 'country'], name='personApp_p_village_19549e_idx'), models.Index(fields=['date_of_birth', 'age'], name='personApp_p_date_of_14eae7_idx'), models.Index(fields=['contact_number', 'place_of_birth', 'birth_time'], name='personApp_p_contact_f42496_idx'), models.Index(fields=['nationality', 'mother_tongue', 'other_language'], name='personApp_p_nationa_44ba14_idx'), models.Index(fields=['cast', 'sub_cast'], name='personApp_p_cast_266e1f_idx'), models.Index(fields=['marital_status', 'gender', 'blood_group', 'family_members'], name='personApp_p_marital_5fa618_idx'), models.Index(fields=['pan_card', 'driving_licence', 'passport_number', 'voting_id'], name='personApp_p_pan_car_495537_idx'), models.Index(fields=['educational_details', 'occupation', 'level'], name='personApp_p_educati_59bd12_idx'), models.Index(fields=['main_photo', 'case_status'], name='personApp_p_main_ph_4553c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Multiple_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='person_photos/')),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personApp.personal_details')),
            ],
            options={
                'indexes': [models.Index(fields=['person_name'], name='personApp_m_person__7f1c87_idx'), models.Index(fields=['photos'], name='personApp_m_photos_7cc2d1_idx')],
            },
        ),
    ]
