# Generated by Django 5.0.7 on 2024-08-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='personal_details',
            name='personApp_p_date_of_14eae7_idx',
        ),
        migrations.AddField(
            model_name='personal_details',
            name='adhar_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='blood_group',
            field=models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='personal_details',
            index=models.Index(fields=['date_of_birth', 'age', 'adhar_number'], name='personApp_p_date_of_22cbf6_idx'),
        ),
    ]
