# Generated by Django 5.0.7 on 2024-08-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0002_remove_personal_details_personapp_p_date_of_14eae7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='adhar_number',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
