# Generated by Django 5.0.7 on 2024-08-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0003_alter_personal_details_adhar_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police_Station_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station_name', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.IntegerField(db_index=True)),
                ('longitude', models.IntegerField(db_index=True)),
                ('address', models.TextField(db_index=True)),
                ('pin_code', models.CharField(db_index=True, max_length=10)),
                ('village', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('taluka', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['police_station_name'], name='personApp_p_police__33366b_idx'), models.Index(fields=['latitude', 'longitude'], name='personApp_p_latitud_47179c_idx'), models.Index(fields=['address', 'pin_code'], name='personApp_p_address_16f897_idx'), models.Index(fields=['village', 'city', 'taluka', 'district'], name='personApp_p_village_687f35_idx'), models.Index(fields=['state', 'country'], name='personApp_p_state_ebf515_idx')],
            },
        ),
    ]
