# Generated by Django 5.0.7 on 2024-08-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0004_police_station_location'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='police_station_location',
            name='personApp_p_police__33366b_idx',
        ),
        migrations.AddField(
            model_name='police_station_location',
            name='police_station_photo',
            field=models.ImageField(blank=True, null=True, upload_to='policeStations/'),
        ),
        migrations.AlterField(
            model_name='police_station_location',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='police_station_location',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AddIndex(
            model_name='police_station_location',
            index=models.Index(fields=['police_station_name', 'police_station_photo'], name='personApp_p_police__1e5d75_idx'),
        ),
    ]
