# Generated by Django 5.0.7 on 2024-08-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0005_remove_police_station_location_personapp_p_police__33366b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_photos',
            name='photos',
            field=models.ImageField(upload_to='person_multiple_photos/'),
        ),
    ]
