# Generated by Django 5.0.7 on 2024-08-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0006_alter_multiple_photos_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_photos',
            name='photos',
            field=models.ImageField(upload_to='person_photos/'),
        ),
    ]
