# Generated by Django 5.0.7 on 2024-08-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0008_police_station_location_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_station_location',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
