# Generated by Django 5.0.7 on 2024-08-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0009_police_station_location_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
