# Generated by Django 5.0.7 on 2024-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0010_personal_details_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='case_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Solved', 'Solved'), ('Closed', 'Closed')], db_index=True, default='Pending', max_length=10, null=True),
        ),
    ]
