# Generated by Django 5.0.7 on 2024-08-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0011_alter_personal_details_case_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police_Complaint_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(db_index=True, max_length=50)),
                ('associate_police_officer_name', models.CharField(db_index=True, max_length=100)),
                ('designation', models.CharField(db_index=True, max_length=50)),
                ('fir_upload', models.FileField(db_index=True, upload_to='FIRs/')),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personApp.personal_details')),
                ('police_station_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personApp.police_station_location')),
            ],
            options={
                'indexes': [models.Index(fields=['person_name', 'fir_number'], name='personApp_p_person__c54fc4_idx'), models.Index(fields=['police_station_name', 'associate_police_officer_name', 'designation'], name='personApp_p_police__3914f1_idx'), models.Index(fields=['fir_upload'], name='personApp_p_fir_upl_464a17_idx')],
            },
        ),
    ]
