# Generated by Django 5.0.7 on 2024-08-22 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0013_police_complaint_details_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_complaint_details',
            name='fir_upload',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to='FIRs/'),
        ),
        migrations.CreateModel(
            name='Missing_Event_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_date', models.DateField(db_index=True)),
                ('missing_time', models.TimeField(db_index=True)),
                ('location_of_missing', models.TextField(db_index=True)),
                ('last_seen_location', models.TextField(db_index=True)),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personApp.personal_details')),
            ],
            options={
                'indexes': [models.Index(fields=['person_name'], name='personApp_m_person__929c14_idx'), models.Index(fields=['missing_date', 'missing_time'], name='personApp_m_missing_484413_idx'), models.Index(fields=['location_of_missing', 'last_seen_location'], name='personApp_m_locatio_f7cab8_idx')],
            },
        ),
    ]
