# Generated by Django 4.2 on 2024-08-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personApp', '0014_alter_police_complaint_details_fir_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_event_details',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
