# Generated by Django 5.0.7 on 2024-08-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0003_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
