# Generated by Django 5.0.7 on 2024-08-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0004_pendinguser_first_name_pendinguser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspension_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
